language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "code-not-found-spring-batch"
    token:
      secure: $SONAR_TOKEN

env:
- PROJECT_DIR=spring-batch-capitalize-names
- PROJECT_DIR=spring-batch-hello-world
- PROJECT_DIR=spring-batch-itemreader
- PROJECT_DIR=spring-batch-itemwriter
- PROJECT_DIR=spring-batch-tasklet
- PROJECT_DIR=spring-batch-admin/spring-batch-task

script:
- cd $PROJECT_DIR
- mvn test -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

notifications:
email: false
